// -*- mode: c++; -*-

#ifndef EXTRACT_EXTRACT_H_
#define EXTRACT_EXTRACT_H_

// LinkDef files generated by rootcint do not include config.h
#if defined(__CINT__) || defined(G__DICTIONARY)
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif // HAVE_CONFIG_H
#endif // defined(__CINT__) || defined(G__DICTIONARY)

#include <iostream>
#include <cmath>
#include <vector>

#include <getClass.h>
#include <Fun4AllServer.h>
#include <Fun4AllInputManager.h>
#include <SubsysReco.h>
#include <RunHeader.h>
#include <EventHeader.h>
#include <PHGlobal.h>
#include <PHCentralTrack.h>
#include <emcClusterContainer.h>
#include <emcClusterContent.h>
#include <ErtOut.h>

//#include <jetevent/xefio.h>
#if !(defined(__CINT__) || defined(G__DICTIONARY))
#include <jetstat/histogram.h>
#endif // !(defined(__CINT__) || defined(G__DICTIONARY))

class tower_statistics_t :
	public SubsysReco
{
private:
	int _nevent;
	std::string _output_filename_spectrum;
	std::string _output_filename_electron;
	std::string _output_filename_tracking;
	std::string _output_filename_tof_histogram;
	std::string _output_filename_tof_electron_histogram;
	std::string _output_filename_tof_hadron_histogram;
	std::string _output_filename_bbc;
	FILE *_output_file_spectrum;
	FILE *_output_file_electron;
	FILE *_output_file_tracking;
	FILE *_output_file_tof_histogram;
	FILE *_output_file_tof_electron_histogram;
	FILE *_output_file_tof_hadron_histogram;
	FILE *_output_file_bbc;
	static const int _ntower = 6 * 36 * 72 + 2 * 48 * 96;
	static const int _nbin_energy = 128 + 1;
	uint64_t _count[_ntower * _nbin_energy];
	void *_tof_histogram;
	void *_tof_electron_histogram;
	void *_tof_hadron_histogram;
public:
	tower_statistics_t(
		std::string output_filename_spectrum = "",
		std::string output_filename_electron = "",
		std::string output_filename_tracking = "",
		std::string output_filename_tof_histogram = "",
		std::string output_filename_tof_electron_histogram = "",
		std::string output_filename_tof_hadron_histogram = "",
		std::string output_filename_bbc = "")
		: SubsysReco("tower_statistics"),
		  _output_filename_spectrum(output_filename_spectrum),
		  _output_filename_electron(output_filename_electron),
		  _output_filename_tracking(output_filename_tracking),
		  _output_filename_tof_histogram(
				output_filename_tof_histogram),
		  _output_filename_tof_electron_histogram(
				output_filename_tof_electron_histogram),
		  _output_filename_tof_hadron_histogram(
				output_filename_tof_hadron_histogram),
		  _output_filename_bbc(output_filename_bbc),
		  _output_file_spectrum(NULL), _output_file_electron(NULL),
		  _output_file_tracking(NULL),
		  _output_file_tof_histogram(NULL),
		  _output_file_tof_electron_histogram(NULL),
		  _output_file_tof_hadron_histogram(NULL),
		  _output_file_bbc(NULL)
	{
		for(int i = 0; i < _ntower * _nbin_energy; i++) {
			_count[i] = 0;
		}
	}

	~tower_statistics_t()
	{
		End(NULL);
	}
	int Init(PHCompositeNode *top_node);
	int InitRun(PHCompositeNode *top_node);
	int process_event(PHCompositeNode *top_node);
	int End(PHCompositeNode *top_node);
};

#endif // EXTRACT_EXTRACT_H_
