AUTOMAKE_OPTIONS = foreign

INCLUDES = -I$(includedir) -I$(OFFLINE_MAIN)/include -I$(ROOTSYS)/include

lib_LTLIBRARIES = \
  libjetAnalyzer.la 

noinst_HEADERS = \
  JetAnalyzerLinkDef.h 

include_HEADERS = \
  JetAnalyzer.h

libjetAnalyzer_la_SOURCES = \
  JetAnalyzer.C \
  JetAnalyzer_Dict.C

libjetAnalyzer_la_LIBADD = \
  -L$(libdir) \
  -L$(OFFLINE_MAIN)/lib \
  -lSubsysReco

# Rule for generating CINT dictionaries from class headers.
JetAnalyzer_Dict.C: \
  JetAnalyzer.h \
  JetAnalyzerLinkDef.h
	rootcint -f $@ -c $(DEFAULT_INCLUDES) $(INCLUDES) $^

clean-local:
	rm -f *Dict*

